### ISSUE TITLE
No response from package after install.

### ISSUE THREAD

**Issue by calynnellington** [vt5491/multi-theme-applicator#7]
I installed this package and was really enjoying it, however it hasn't worked again after the initial installation. The hotkeys do not work anymore and when trying to access the package via the command palate the package hangs. I haven't received any error messages so this may be something with my local install that is causing the issue. I will update this if I resolve the problem.

**Comment by vt5491** [comment]
You might want to try reinstalling the package using the apm line command.  apm is a line command that ships with all atom editor  installations. It basically just let you manage your packages without without having to be inside the Atom editor itself.   

 So open up a command prompt, and  try “apm list”  to see a list of packages (‘apm —help’ will show all the commands).   Then try “apm install multi-theme-applicator’ (you may need to uninstall it if it’s already installed). Try this with the Atom editor not active.   Sometimes you just get a cleaner install when you use apm and the editor is not up e.g. there are no conflicts such as locking issues.   I’ve had cases with some big packages where I had to use apm to get them properly installed .

 Unfortunately, I’m not at a computer right now so I can’t give you much more detail. But basically I would just recommend uninstalling and reinstalling using apm and see if that works.

**Comment by vt5491** [comment]
Also make sure that when you’re trying to apply a theme you have an active file open. If you try to apply or invoke MTA when there’s no active editors open or you’re trying to apply it against the config settings panel it won’t work right. So make sure you have an open JavaScript file or something opened and with keyboard focus before you invoke multi theme applicator.

**Comment by calynnellington** [comment]
I've got files open so that wasn't the issue. I've reinstalled using apm and that seems to have done the trick. Great package, I really enjoy mixing syntax themes and using them to color code my work space.

**Comment by vt5491** [comment]
Fantastic, and thank you for your support.
